cinetopia/cinema/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('movies/', views.MoviesView.as_view(), name='movies'),
    path('movies/search/', views.movie_search, name='movie_search'),
    path('movies/rating/', views.rate_movie, name='rate-movie'),
    path('movies/<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('movies/<int:pk>/stream/', views.get_streaming_video, name='movie-stream'),
]

cinetopia/cinetopia/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cinetopia import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('cinema.urls')),
    path('', include('shop.urls')),
    path('', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cinetopia/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('shop/', views.ProductsListView.as_view(), name='shop'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('cart/', views.cart_detail, name='cart_detail'),
]

cinetopia/cinema/models.py
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator, MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.text import slugify

User = get_user_model()


class Country(models.Model):
    name = models.CharField(unique=True, max_length=100)

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(unique=True, max_length=50)

    def __str__(self):
        return self.name

class MovieType(models.Model):
    CONTENT_TYPES = [
        ('movie', 'Фильм'),
        ('series', 'Сериал'),
        ('cartoon', 'Мультфильм'),
        ('anime', 'Аниме'),
        ('documentary', 'Документальный'),
        ('tv_show', 'ТВ-шоу'),
    ]

    name = models.CharField(
        max_length=20,
        choices=CONTENT_TYPES,
        unique=True
    )

    def __str__(self):
        return self.name


class Movie(models.Model):
    CONTENT_TYPES = [
        ('movie', 'Фильм'),
        ('series', 'Сериал'),
        ('cartoon', 'Мультфильм'),
        ('anime', 'Аниме'),
        ('documentary', 'Документальный'),
        ('tv_show', 'ТВ-шоу'),
    ]
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    title = models.CharField(max_length=255)
    original_title = models.CharField(max_length=255, blank=True, null=True)
    release_year = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    poster = models.ImageField(
        upload_to='posters/',
        validators=[FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])],
        blank=True,
        null=True
    )
    movie_file = models.FileField(
        upload_to='movies/',
        validators=[FileExtensionValidator(['mp4', 'mkv', 'webm'])],
        blank=True,
        null=True
    )
    duration = models.IntegerField(blank=True, null=True)
    type = models.CharField(max_length=20, choices=CONTENT_TYPES)
    added_by = models.ForeignKey(User, models.CASCADE, blank=True, null=True)
    added_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    genres = models.ManyToManyField('Genre', related_name='movies', blank=True)
    countries = models.ManyToManyField('Country', related_name='movies', blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.original_title}-{self.release_year}")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Movie: {self.title} ({self.original_title})"


class Rating(models.Model):
    movie = models.ForeignKey('Movie', models.CASCADE, related_name='ratings')
    user = models.ForeignKey(User, models.CASCADE, related_name='ratings')
    rating = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(10)])

    class Meta:
        unique_together = (('movie', 'user'),)

    def __str__(self):
        return f"{self.movie} - {self.user} ({self.rating})"

class UserMovieList(models.Model):
    LIST_TYPES = [
        ('watched', 'Просмотрено'),
        ('watching', 'Просматривается'),
        ('delayed', 'Отложено'),
        ('abandoned', 'Брошено'),
        ('favorite', 'Избранное'),
    ]
    user = models.ForeignKey(User, models.CASCADE, related_name='lists')
    movie = models.ForeignKey('Movie', models.CASCADE, related_name='lists')
    list_type = models.CharField(max_length=20, choices=LIST_TYPES)
    added_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('user', 'movie'),)

    def __str__(self):
        return f"{self.movie} - {self.user} ({self.list_type})"

    @property
    def list_type_name(self):
        return self.get_list_type_display()

cinetopia/cinema/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Q
from django.db.models.functions import Coalesce
from django.http import StreamingHttpResponse, JsonResponse
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView, TemplateView

from cinema.filters import MovieFilter
from cinema.models import Movie, Genre, Country, Rating, UserMovieList
from cinema.services import open_file
from cinema.sorters import MovieSorter


class HomeView(TemplateView):
    template_name = 'cinema/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        base_queryset = Movie.objects.filter(
            is_active=True
        ).annotate(
            avg_rating=Avg('ratings__rating')
        ).prefetch_related(
            'ratings',
            'genres',
        )
        context_data['popular_movies'] = base_queryset.order_by('-avg_rating')[:15]
        context_data['new_movies'] = base_queryset.order_by('-release_year')[:15]

        return context_data


class MoviesView(ListView):
    template_name = 'cinema/movies.html'
    context_object_name = 'movies'
    paginate_by = 15
    filter_class = MovieFilter
    sorter_class = MovieSorter

    def get_queryset(self):
        queryset = Movie.objects.filter(
            is_active=True
        ).prefetch_related(
            'ratings',
            'genres',
            'countries'
        ).annotate(
            avg_rating=Coalesce(Avg('ratings__rating'), 0.0)
        )
        filters = self._extract_filters_from_request()
        queryset = self.filter_class.apply_custom_filters(queryset, filters)
        return self.sorter_class.apply_sorting(queryset, filters.get('selected_sort'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        filters = self._extract_filters_from_request()

        context.update({
            'genres': Genre.objects.all(),
            'countries': Country.objects.all(),
            'years': self._get_available_years(),
            'content_types': Movie.CONTENT_TYPES,
            **filters
        })
        return context

    def _extract_filters_from_request(self):
        request = self.request
        rating_range = request.GET.get('rating', '0,10').split(',')
        selected_year = request.GET.get('year', '')

        return {
            'selected_genres': request.GET.getlist('genre'),
            'selected_types': request.GET.getlist('type'),
            'selected_year': int(selected_year) if selected_year.isdigit() else 0,
            'selected_country': request.GET.get('country'),
            'min_rating': float(rating_range[0]),
            'max_rating': float(rating_range[1]),
            'selected_sort': request.GET.get('sort', '-rating'),
            'search_query': request.GET.get('search_query')
        }

    @staticmethod
    def _get_available_years():
        return Movie.objects.filter(
            is_active=True
        ).order_by(
            '-release_year'
        ).values_list(
            'release_year',
            flat=True
        ).distinct()


class MovieDetailView(DetailView):
    template_name = 'cinema/movie_detail.html'
    queryset = Movie.objects.filter(
        is_active=True
    ).annotate(
        avg_rating=Avg('ratings__rating')
    ).prefetch_related(
        'ratings',
        'genres',
    )
    context_object_name = 'movie'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context.update({
                'user_rating': Rating.objects.filter(
                    movie=self.object,
                    user=self.request.user
                ).first(),
                'list_types': UserMovieList.LIST_TYPES
            })
        return context


def get_streaming_video(request, pk: int):
    file, status_code, content_length, content_range = open_file(request, pk)
    response = StreamingHttpResponse(file, status=status_code, content_type='video/mp4')
    response['Accept-Ranges'] = 'bytes'
    response['Content-Length'] = str(content_length)
    response['Cache-Control'] = 'no-cache'
    response['Content-Range'] = content_range

    return response


def movie_search(request):
    query = request.GET.get('query', '')
    if query:
        movies = Movie.objects.filter(
            Q(title__icontains=query) &
            Q(is_active=True)
        ).prefetch_related('genres')[:10]

        results = [{
            'title': movie.title,
            'slug': movie.slug,
            'poster': movie.poster.url if movie.poster else '',
            'release_year': movie.release_year
        } for movie in movies]
    else:
        results = []

    return JsonResponse({'movies': results})


@require_POST
@login_required
def rate_movie(request):
    movie_id = request.POST.get('movie_id')
    rating = request.POST.get('rating')

    try:
        movie = Movie.objects.get(pk=movie_id)
        rating = int(rating)

        if rating < 1 or rating > 10:
            return JsonResponse({'success': False, 'error': 'Оценка должна быть от 1 до 10'})

        Rating.objects.update_or_create(
            movie=movie,
            user=request.user,
            defaults={'rating': rating}
        )

        return JsonResponse({'success': True})

    except Movie.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Фильм не найден'})
    except ValueError:
        return JsonResponse({'success': False, 'error': 'Некорректная оценка'})

cinetopia/cinema/templates/cinema/base.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>{% block title %} {% endblock %}</title>
  <link rel="stylesheet" href="{% static 'cinema/css/styles.css' %}">
  <link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet"/>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  {% block head %} {% endblock %}
  {% block style %}{% endblock %}
</head>
<body>
<header>
  <div class="container">
    <a class='main-title' href="{% url 'home' %}">🎟️Cinetopia</a>
    <nav>
      <ul>
        <li><a href="{% url 'movies' %}">Фильмы</a></li>
        <li class="search-container">
          <input type="text" id="movie-search" placeholder="Название фильма">
          <div id="search-results" class="search-results"></div>
        </li>
        <li><a href="/">Главная</a></li>
        <li><a href="/about/">О нас</a></li>
        <li><a href="/contact/">Контакты</a></li>
        <li><a href="/shop/">Магазин</a></li>
        <li>
          <a href="{% url 'cart_detail' %}" class="cart-link" id="cart">
            🛒
            {% if cart|length > 0 %}
              <span class="cart-count">{{ cart|length }}</span>
            {% endif %}
          </a>
        </li>
        <li class="auth-links">
          {% if user.is_authenticated %}
            <a href="{% url 'account' %}"><span class="username">Привет, <strong>{{ user.username }}</strong>!</span></a>
            <form action="{% url 'logout' %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="logout-btn">Выйти</button>
            </form>
          {% else %}
            <a href="{% url 'login' %}" class="login-btn">Войти</a>
            <a href="{% url 'register' %}" class="register-btn">Регистрация</a>
          {% endif %}
        </li>
      </ul>
    </nav>
  </div>
</header>
{% block main %}
  <main></main>
{% endblock %}

<script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>
<script>
    $(document).ready(function () {
        $('#movie-search').on('input', function () {
            const query = $(this).val().trim();
            if (query.length >= 2) {
                $.ajax({
                    url: '{% url "movie_search" %}',
                    data: {
                        'query': query
                    },
                    dataType: 'json',
                    success: function (data) {
                        const results = $('#search-results');
                        results.empty();
                        if (data.movies.length > 0) {
                            data.movies.forEach(function (movie) {
                                results.append(
                                    `<a href="/movies/${movie.slug}/" class="search-result-item">
                  <img src="${movie.poster}" alt="${movie.title}">
                  <span>${movie.title} (${movie.release_year})</span>
                </a>`
                                );
                            });
                            results.show();
                        } else {
                            results.append('<div class="no-results">Ничего не найдено</div>');
                            results.show();
                        }
                    }
                });
            } else {
                $('#search-results').hide();
            }
        });

        $(document).on('click', function (e) {
            if (!$(e.target).closest('.search-container').length) {
                $('#search-results').hide();
            }
        });
    });
</script>
{% block scripts %}

{% endblock %}
<footer>
  <div class="container">
    <p>&copy; 2025 Cinetopia. Все права защищены.</p>
  </div>
</footer>
</body>
</html>

cinetopia/cinema/templates/cinema/index.html
{% extends 'cinema/base.html' %}
{% load static %}
{% load cinema_tags %}

{% block title %}Главная страница{% endblock %}

{% block main %}
  <main>
    {% movie_carousel new_movies "Новые фильмы" %}
    {% movie_carousel popular_movies "Популярные фильмы" %}
  </main>
{% endblock %}
{% block scripts %}
  <script>
      document.addEventListener('DOMContentLoaded', function () {
          function initCarousel(carouselContainer) {
              const carousel = carouselContainer.querySelector('.movie-list');
              const prevBtn = carouselContainer.querySelector('.carousel-btn.prev');
              const nextBtn = carouselContainer.querySelector('.carousel-btn.next');
              const movieItems = carousel.querySelectorAll('.movie-item');

              if (movieItems.length === 0) return;

              const itemWidth = movieItems[0].offsetWidth + 20; 
              let position = 0;
              const maxPosition = -itemWidth * (movieItems.length - 5);

              function updateButtons() {
                  prevBtn.disabled = position === 0;
                  nextBtn.disabled = position <= maxPosition;
              }

              prevBtn.addEventListener('click', function () {
                  if (position < 0) {
                      position += itemWidth;
                      carousel.style.transform = `translateX(${position}px)`;
                      updateButtons();
                  }
              });

              nextBtn.addEventListener('click', function () {
                  if (position > maxPosition) {
                      position -= itemWidth;
                      carousel.style.transform = `translateX(${position}px)`;
                      updateButtons();
                  }
              });

              updateButtons();
          }

          document.querySelectorAll('.carousel').forEach(initCarousel);
      });
  </script>
{% endblock %}

cinetopia/cinema/templates/cinema/movie_detail.html
{% extends 'cinema/base.html' %}
{% load static %}

{% block title %}{{ movie.title }} - Cinetopia{% endblock %}
{% block head %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
{% endblock %}
{% block style %}
  <link rel="stylesheet" href="{% static 'cinema/css/movie_detail.css' %}">
{% endblock %}

{% block main %}
  <main class="movie-detail">
    <div class="container">
      <div class="movie-header">
        <div class="movie-poster">
          <img src="{{ movie.poster.url }}" alt="{{ movie.title }}">
        </div>
        <div class="movie-info">
          <h1>{{ movie.title }}</h1>
          {% if movie.original_title %}
            <h2 class="original-title">{{ movie.original_title }}</h2>
          {% endif %}

          <div class="meta-info">
            <span class="release-year">{{ movie.release_year }}</span>
            <span class="duration">{{ movie.duration|default_if_none:"-" }} мин.</span>
            <span class="type">{{ movie.get_type_display }}</span>
          </div>

          <div class="rating-block">
            {% if movie.avg_rating %}
              <div class="rating rating-{{ movie.avg_rating|floatformat:"0" }}">
                {{ movie.avg_rating|floatformat:1 }}
              </div>
            {% else %}
              <div class="rating rating-none" style="color: #ddd">Нет оценок</div>
            {% endif %}
            {% if user.is_authenticated %}
              {% if not user_rating %}
                <div class="custom-rating">
                  <div class="stars-container">
                    {% for i in "0123456789" %}
                      <span class="star" data-value="{{ forloop.counter }}">★</span>
                    {% endfor %}
                  </div>
                  <span class="rating-value"><span id="selected-rating">0</span>/10</span>
                  <button class="rate-btn" id="submit-rating" disabled>Оценить</button>
                </div>
              {% else %}
                <div class="user-rating">
                  <span>Ваша оценка:</span> <span
                        class="rating rating-{{ user_rating.rating|floatformat:0 }}">{{ user_rating.rating }}</span>
                </div>
              {% endif %}
            {% endif %}
          </div>

          <div class="genres">
            {% for genre in movie.genres.all %}
              <span class="tag">{{ genre.name }}</span>
            {% endfor %}
          </div>

          <div class="countries">
            {% for country in movie.countries.all %}
              <span class="tag">{{ country.name }}</span>
            {% endfor %}
          </div>
          {% if user.is_authenticated %}
            <div class="user-movie-list">
              <label for="movie-list">Добавить в список</label>
              <select id="movie-list" name="movie-list">
                <option value="">Выберите список</option>
                {% for list_type in list_types %}
                  <option value="{{ list_type.0 }}">{{ list_type.1 }}</option>
                {% endfor %}
              </select>
            </div>
          {% endif %}
        </div>
      </div>

      <div class="movie-content">
        <div class="description">
          <h3>Описание</h3>
          <p>{{ movie.description|default:"Описание отсутствует" }}</p>
        </div>

        <div class="player">
          <video
                  id="video"
                  class="video-js"
                  controls
                  preload="auto"
                  width="700"
                  height="500"
                  data-setup="{}"
                  poster="{{ random_frame_url|default:movie.poster.url }}"
          >
            <source src="{% url 'movie-stream' movie.id %}" type="video/mp4"/>
            <source src="{% url 'movie-stream' movie.id %}" type="video/webm"/>
            Не удалось загрузить видео
          </video>
        </div>

      </div>
    </div>
  </main>
{% endblock %}
{% block scripts %}
  <script>
      document.addEventListener('DOMContentLoaded', function () {
          const stars = document.querySelectorAll('.star');
          const ratingValue = document.getElementById('selected-rating');
          const submitBtn = document.getElementById('submit-rating');

          if (stars.length > 0) {
              let currentRating = 0;
              let hoverRating = 0;

              stars.forEach(star => {
                  star.addEventListener('mouseover', function () {
                      hoverRating = parseInt(this.getAttribute('data-value'));
                      updateStars();
                  });

                  star.addEventListener('mouseout', function () {
                      hoverRating = 0;
                      updateStars();
                  });

                  star.addEventListener('click', function () {
                      currentRating = parseInt(this.getAttribute('data-value'));
                      ratingValue.textContent = currentRating;
                      submitBtn.disabled = false;
                      updateStars();
                  });
              });

              function updateStars() {
                  const rating = hoverRating || currentRating;

                  stars.forEach(star => {
                      const value = parseInt(star.getAttribute('data-value'));
                      if (value <= rating) {
                          star.style.color = '#ffd700';
                          star.style.textShadow = '0 0 5px rgba(255, 215, 0, 0.5)';
                      } else {
                          star.style.color = '#d8d8d8'; 
                          star.style.textShadow = 'none';
                      }
                  });
              }

              submitBtn.addEventListener('click', function () {
                  const movieId = "{{ movie.id }}";
                  fetch("{% url 'rate-movie' %}", {
                      method: "POST",
                      headers: {
                          'Content-Type': 'application/x-www-form-urlencoded',
                          'X-CSRFToken': "{{ csrf_token }}"
                      },
                      body: `movie_id=${movieId}&rating=${currentRating}`
                  })
                      .then(response => response.json())
                      .then(data => {
                          if (data.success) {
                              location.reload();
                          } else {
                              alert("Ошибка: " + (data.error || "Неизвестная ошибка"));
                          }
                      })
                      .catch(() => {
                          alert("Произошла ошибка при отправке оценки");
                      });
              });
          }
      });
  </script>
  <script>
      $(document).ready(function () {
          $('select').select2({
              theme: 'default',
              minimumResultsForSearch: Infinity,
              width: 'auto',
              dropdownAutoWidth: true
          });
      });
  </script>
{% endblock %}