cinetopia/cinetopia/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cinetopia import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('cinema.urls')),
    path('', include('shop.urls')),
    path('', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cinetopia/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('shop/', views.ProductsListView.as_view(), name='shop'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('cart/', views.cart_detail, name='cart_detail'),
]

cinetopia/user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', views.AccountView.as_view(), name='account'),
]

cinetopia/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Attributes(models.Model):
    name = models.CharField(unique=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'attributes'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Countries(models.Model):
    name = models.CharField(unique=True, max_length=100)

    class Meta:
        managed = False
        db_table = 'countries'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Genres(models.Model):
    name = models.CharField(unique=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'genres'


class MovieAttributes(models.Model):
    movie = models.OneToOneField('Movies', models.DO_NOTHING, primary_key=True)  # The composite primary key (movie_id, attribute_id) found, that is not supported. The first column is selected.
    attribute = models.ForeignKey(Attributes, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'movie_attributes'
        unique_together = (('movie', 'attribute'),)


class MovieCountries(models.Model):
    movie = models.OneToOneField('Movies', models.DO_NOTHING, primary_key=True)  # The composite primary key (movie_id, country_id) found, that is not supported. The first column is selected.
    country = models.ForeignKey(Countries, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'movie_countries'
        unique_together = (('movie', 'country'),)


class MovieGenres(models.Model):
    movie = models.OneToOneField('Movies', models.DO_NOTHING, primary_key=True)  # The composite primary key (movie_id, genre_id) found, that is not supported. The first column is selected.
    genre = models.ForeignKey(Genres, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'movie_genres'
        unique_together = (('movie', 'genre'),)


class MovieTypes(models.Model):
    name = models.CharField(unique=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'movie_types'


class Movies(models.Model):
    title = models.CharField(max_length=255)
    original_title = models.CharField(max_length=255, blank=True, null=True)
    release_year = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    poster_url = models.CharField(max_length=255, blank=True, null=True)
    movie_file_url = models.CharField(max_length=255, blank=True, null=True)
    duration = models.IntegerField(blank=True, null=True, db_comment='продолжительность в минутах')
    type = models.ForeignKey(MovieTypes, models.DO_NOTHING, blank=True, null=True)
    added_by = models.ForeignKey('Users', models.DO_NOTHING, db_column='added_by', blank=True, null=True)
    added_date = models.DateTimeField(blank=True, null=True)
    is_active = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'movies'


class Ratings(models.Model):
    movie = models.ForeignKey(Movies, models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey('Users', models.DO_NOTHING, blank=True, null=True)
    rating = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ratings'
        unique_together = (('movie', 'user'),)


class Roles(models.Model):
    name = models.CharField(unique=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'roles'


class UserMovieLists(models.Model):
    user = models.ForeignKey('Users', models.DO_NOTHING, blank=True, null=True)
    movie = models.ForeignKey(Movies, models.DO_NOTHING, blank=True, null=True)
    list_type = models.CharField(max_length=11)
    added_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user_movie_lists'
        unique_together = (('user', 'movie'),)


class Users(models.Model):
    username = models.CharField(unique=True, max_length=50)
    email = models.CharField(unique=True, max_length=100)
    password_hash = models.CharField(max_length=255)
    role = models.ForeignKey(Roles, models.DO_NOTHING)
    registration_date = models.DateTimeField(blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    is_active = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'users'

cinetopia/orders/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from shop.models import Product


class Order(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Ожидает обработки'),
        ('processing', 'В обработке'),
        ('shipped', 'Отправлен'),
        ('completed', 'Завершен'),
        ('cancelled', 'Отменен'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='orders'
    )
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100, default='Россия')
    phone = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    paid = models.BooleanField(default=False)
    note = models.TextField(blank=True)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost * (100 - self.discount) / 100

    def get_total_quantity(self):
        return sum(item.quantity for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        related_name='items',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Product,
        related_name='order_items',
        on_delete=models.SET_NULL,
        null=True
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return (self.price * (100 - self.discount) / 100) * self.quantity

cinetopia/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    pass

cinetopia/user/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView as BaseLoginView
from django.db.models import Count, F, Case, When, CharField, Value
from django.shortcuts import redirect
from django.views.generic import FormView, TemplateView

from cinema.models import UserMovieList
from orders.models import Order
from .forms import RegisterForm, LoginForm


class LoginView(BaseLoginView):
    form_class = LoginForm
    template_name = 'user/login.html'


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'user/register.html'
    success_url = '/'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())


class AccountView(TemplateView):
    template_name = 'user/account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        movie_stats = UserMovieList.objects.filter(user=user).values(
            'list_type'
        ).annotate(
            count=Count('id'),
            list_name=Case(
                *[
                    When(list_type=list_type, then=Value(value))
                    for list_type, value in UserMovieList.LIST_TYPES
                ],
                output_field=CharField()
            )
        ).order_by('list_type')

        context['movie_stats'] = movie_stats
        context['recent_orders'] = Order.objects.filter(user=user).order_by('-created')[:3]
        context['recent_movies'] = UserMovieList.objects.filter(
            user=user
        ).select_related('movie').order_by('-added_at')[:4]

        return context

cinetopia/user/templates/user/account.html
{% extends "cinema/base.html" %}
{% load static %}

{% block title %}
  Личный кабинет | 🎟️Cinetopia
{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static "user/css/account.css" %}">
{% endblock %}
{% block main %}
<main class="account-container">
    <div class="account-sidebar">
      <div class="account-header">
        <div class="account-avatar">
          {% if user.profile.avatar %}
            <img src="{{ user.profile.avatar.url }}" alt="{{ user.username }}">
          {% else %}
            <div class="avatar-placeholder">{{ user.username|first|upper }}</div>
          {% endif %}
        </div>
        <h1 class="account-username">{{ user.username }}</h1>
        <a href="#" class="edit-profile-btn">Редактировать профиль</a>
      </div>
      
      <nav class="account-nav">
        <ul>
          <li class="active"><a href="#profile">Профиль</a></li>
          <li><a href="#movies">Мои фильмы</a></li>
          <li><a href="#orders">Мои заказы</a></li>
          <li><a href="#settings">Настройки</a></li>
        </ul>
      </nav>
    </div>
    
    <div class="account-content">
      <section id="profile" class="account-section">
        <h2 class="section-title">Мой профиль</h2>
        <div class="profile-info">
          <div class="info-row">
            <span class="info-label">Имя:</span>
            <span class="info-value">{{ user.first_name|default:"Не указано" }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">Фамилия:</span>
            <span class="info-value">{{ user.last_name|default:"Не указано" }}</span>
          </div>
          <div class="info-row">
            <span class="info-label">Email:</span>
            <span class="info-value">{{ user.email }}</span>
          </div>
          {% if user.profile.birth_date %}
            <div class="info-row">
              <span class="info-label">Дата рождения:</span>
              <span class="info-value">{{ user.profile.birth_date|date:"d.m.Y" }}</span>
            </div>
          {% endif %}
          {% if user.profile.phone %}
            <div class="info-row">
              <span class="info-label">Телефон:</span>
              <span class="info-value">{{ user.profile.phone }}</span>
            </div>
          {% endif %}
          {% if user.profile.bio %}
            <div class="info-row">
              <span class="info-label">О себе:</span>
              <p class="info-bio">{{ user.profile.bio }}</p>
            </div>
          {% endif %}
        </div>
      </section>
      
      <section id="movies" class="account-section">
        <h2 class="section-title">Мои фильмы</h2>
        
        <div class="movie-stats">
          {% for stat in movie_stats %}
            <div class="stat-item">
              <span class="stat-count">{{ stat.count }}</span>
              <span class="stat-label">{{ stat.list_name }}</span>
            </div>
          {% endfor %}
        </div>
        
        <h3 class="subsection-title">Недавно добавленные</h3>
        <div class="recent-movies">
          {% for item in recent_movies %}
            <div class="movie-card">
              <a href="{{ item.movie.get_absolute_url }}">
                {% if item.movie.poster %}
                  <img src="{{ item.movie.poster.url }}" alt="{{ item.movie.title }}">
                {% else %}
                  <div class="movie-poster-placeholder"></div>
                {% endif %}
                <span class="movie-badge {{ item.list_type }}">{{ item.get_list_type_display }}</span>
                <h4 class="movie-title">{{ item.movie.title }}</h4>
              </a>
            </div>
          {% empty %}
            <p class="empty-message">Вы еще не добавили ни одного фильма</p>
          {% endfor %}
        </div>
        
        <a href="/" class="view-all-link">Смотреть все →</a>
      </section>
      
      <section id="orders" class="account-section">
        <h2 class="section-title">Мои заказы</h2>
        
        {% if recent_orders %}
          <div class="orders-list">
            {% for order in recent_orders %}
              <div class="order-card">
                <div class="order-header">
                  <span class="order-number">Заказ #{{ order.id }}</span>
                  <span class="order-date">{{ order.created|date:"d.m.Y" }}</span>
                  <span class="order-status {{ order.status }}">{{ order.get_status_display }}</span>
                </div>
                <div class="order-total">Сумма: {{ order.get_total_cost }} ₽</div>
                <a href="{% url 'order_detail' order.id %}" class="order-details-link">Подробнее</a>
              </div>
            {% endfor %}
          </div>
          <a href="{% url 'user_orders' %}" class="view-all-link">Смотреть все →</a>
        {% else %}
          <p class="empty-message">У вас пока нет заказов</p>
        {% endif %}
      </section>
    </div>
  </main>
{% endblock %}

cinetopia/user/templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'user/css/styles.css' %}">
  {% block head %} {% endblock %}
  {% block style %}{% endblock %}
</head>
<body>
  {% block main %}{% endblock %}
</body>
{% block scripts %}{% endblock %}
</html>

cinetopia/user/templates/user/login.html
{% extends 'user/base.html' %}
{% block title %}Авторизация | Cinetopia{% endblock %}
{% block main %}
  <main>
    <div class="auth-form">
      <h2>Вход</h2>

      <form method="post">
        {% csrf_token %}

        {% if form.errors %}
          <ul class="errorlist">
            <li>Неверное имя пользователя или пароль. Попробуйте снова.</li>
          </ul>
        {% endif %}

        <div class="form-group">
          <label for="id_username">Имя пользователя</label>
          {{ form.username }}
        </div>

        <div class="form-group">
          <label for="id_password">Пароль</label>
          {{ form.password }}
        </div>

        <button type="submit" class="btn">Войти</button>
      </form>

      <div class="auth-links">
        Нет аккаунта? <a href="{% url 'register' %}">Зарегистрироваться</a>
      </div>
    </div>
  </main>
{% endblock %}

cinetopia/user/templates/user/register.html
{% extends 'user/base.html' %}
{% block title %}Регистрация | Cinetopia{% endblock %}
{% block main %}
  <main>
    <div class="auth-form">
      <h2>Регистрация</h2>

      <form method="post">
        {% csrf_token %}

        {% if form.errors %}
          <ul class="errorlist">
            {% for field in form %}
              {% for error in field.errors %}
                <li>{{ error }}</li>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        <div class="form-group">
          <label for="id_username">Имя пользователя</label>
          {{ form.username }}
        </div>

        <div class="form-group">
          <label for="id_email">Email</label>
          {{ form.email }}
        </div>

        <div class="form-group">
          <label for="id_password1">Пароль</label>
          {{ form.password1 }}
        </div>

        <div class="form-group">
          <label for="id_password2">Подтверждение пароля</label>
          {{ form.password2 }}
        </div>

        <button type="submit" class="btn">Зарегистрироваться</button>
      </form>

      <div class="auth-links">
        Уже есть аккаунт? <a href="{% url 'login' %}">Войти</a>
      </div>
    </div>
  </main>
{% endblock %}